---
- hosts: directory_cluster
  remote_user: root
  become: yes
  become_method: su
  tasks:
    # Create a container using overlayfs, create an archive of it, create a
    # snapshot clone of the container and and finally leave the container
    # in a frozen state. The container archive will be compressed using gzip.
    # -- Straight outta Docston -- Ansible Docs son --
    - name: Create an overlayfs container archive and clone it
      lxc_container:
        name: test-container-overlayfs
        container_log: true
        template: ubuntu
        state: started
        backing_store: overlayfs
        template_options: --release trusty
        clone_snapshot: true
        clone_name: test-container-overlayfs-clone-snapshot
        archive: true
        archive_compression: gzip

          
