---

- name: Ensure we have the required packages
  apt: name=python-pip state=present
  tags: python

- pip:  name=lxc-python2 state=present # requirement for 'lxc_containers' extras module
  
- name: Ensure lxc is installed and current version
  apt: name=lxc state=present
  tags: lxc

- name: Ensure lxc-dev is installed and current version
  apt: name=lxc-dev state=present
  tags: lxc

