---

- name: Create a new container to house our web application, archive it
  lxc_container:
    name: test-container-rvmrails-dev
    container_log: true
    template: ubuntu
    state: started
    backing_store: dir
    template_options: --release trusty
    archive: true
    archive_compression: gzip

#- name: Install rvm on container
      
 # - name: write the apache config file
 #   template:
 #     src=/srv/apache2.j2
 #     dest=/etc/apache2.conf
